# Dependencies
markdown:         kramdown
highlighter:      pygments
plugins: [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Ambika Gopalan
tagline:          ''
description:      ''
url:              http://ambikagopalan.com
baseurl:          /

author:
  name:           'Ambika Gopalan'
  url:            http://ambikagopalan.com

paginate:         5

# Custom vars
version:          2.1.0

blog:			  'https://designbetter.substack.com/'

github:
  repo:           https://github.com/ambika-gopalan/
