# Dependencies
markdown:         kramdown
highlighter:      pygments
gem: [jekyll-paginate, jekyll-gists]

# Permalinks
permalink:        pretty

# Setup
title:            Ambika Gopalan
tagline:          ''
description:      ''
url:              http://ambikagoplan.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
